### ISSUE TITLE
Make master branch minimal

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/audpc_example#2]
This would involve having 4 files
- R script
- .gitignore
- docx file
- .Rproj file

Note, that the docx format is not well suited for git and [problems do occur when attempting to merge diffs of binary files](https://twitter.com/ClausWilke/status/743464851750584320).

The rationale behind this is to get the students to replicate the docx file as an Rmarkdown document. On a separate branch, we will have the Rmarkdown document in place. 

Steps:
- create new branch with code as it is
- rewrite Rmarkdown as report
- create new branch
- generate docx file and remove Rmarkdown file
- merge that branch with master

**Comment by zkamvar** [comment]
ping

**Comment by zachary-foster** [comment]
Yea, I had planned to remove the rmd before the workshop. I will do what you suggest this weekend. Thanks!

**Comment by zkamvar** [comment]
Whoops. I meant to ping the pull request
